CREATE TABLESPACE stack_overflow 
  DATAFILE '/u01/app/oracle/oradata/cdb1/stack_overflow.dbf'
  SIZE 10G
  AUTOEXTEND ON;
ALTER TABLESPACE stack_overflow NOLOGGING;

CREATE USER DUMMY IDENTIFIED BY DUMMYPASSWORD
DEFAULT TABLESPACE stack_overflow;
ALTER USER DUMMY QUOTA UNLIMITED ON stack_overflow;

GRANT CREATE SESSION TO DUMMY;

/* to clean up:

DROP USER DUMMY CASCADE ;
DROP TABLESPACE stack_overflow INCLUDING CONTENTS AND DATAFILES ;
 */


