CREATE TABLE DUMMY.link_types (
	link_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	type NVARCHAR2(40) NOT NULL,
	CONSTRAINT link_types_pk PRIMARY KEY (link_type_id)
);

CREATE TABLE DUMMY.vote_types (
	vote_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name NVARCHAR2(40) NOT NULL,
	CONSTRAINT vote_types_pk PRIMARY KEY (vote_type_id)
);

CREATE TABLE DUMMY.post_types (
	post_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	type NVARCHAR2(40) NOT NULL,
	CONSTRAINT post_types_pk PRIMARY KEY (post_type_id)
);

CREATE TABLE DUMMY.post_tags (
	post_id NUMBER NOT NULL,
	tag NVARCHAR2(50) NOT NULL,
	CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag)
);

INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(3,  'DownMod');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(2,  'UpMod');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(4,  'Offensive');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(1,  'AcceptedByOriginator');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(5,  'Favorite');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(6,  'Close');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(7,  'Reopen');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(8,  'BountyStart');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(9,  'BountyClose');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(10, 'Deletion');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(11, 'Undeletion');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(12, 'Spam');
INSERT INTO DUMMY.vote_types (vote_type_id, name) VALUES(13, 'InformModerator');

INSERT INTO DUMMY.post_types (post_type_id, type) VALUES(2, 'Answer') ;
INSERT INTO DUMMY.post_types (post_type_id, type) VALUES(1, 'Question') ;

INSERT INTO DUMMY.link_types (link_type_id, type) VALUES(1, 'Linked') ;
INSERT INTO DUMMY.link_types (link_type_id, type) VALUES(3, 'Duplicate') ;

/* TODO: Full Text Indexes */

CREATE TABLE DUMMY.votes (
	vote_id NUMBER GENERATED ALWAYS AS IDENTITY,
	post_id NUMBER NOT NULL,
	user_id NUMBER NULL,
	bount_amount NUMBER NULL,
	vote_type_id NUMBER NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT votes_pk PRIMARY KEY (vote_id)
);

CREATE TABLE DUMMY.users (
	user_id NUMBER GENERATED ALWAYS AS IDENTITY,
	age NUMBER NULL,
	created_at TIMESTAMP NOT NULL,
	display_name NVARCHAR2(40) NOT NULL,
	down_votes NUMBER NOT NULL,
	email_hash NVARCHAR2(40),
	last_access_date TIMESTAMP NOT NULL,
	location NVARCHAR2(100) NULL,
	reputation NUMBER NOT NULL,
	up_votes NUMBER NOT NULL,
	views NUMBER NOT NULL,
	website_url NVARCHAR2(255) NULL,
	account_id NUMBER NULL,
	about_me NCLOB NULL,
	CONSTRAINT users_pk PRIMARY KEY (user_id)
);

CREATE TABLE DUMMY.posts (
	post_id NUMBER GENERATED ALWAYS AS IDENTITY,
	accepted_answer_id NUMBER NULL,
	answer_count NUMBER NULL,
	closed_date TIMESTAMP NULL,
	comment_count NUMBER NULL,
	community_owned_date TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL,
	favorite_count NUMBER NULL,
	last_activity_date TIMESTAMP NOT NULL,
	last_edit_date TIMESTAMP NULL,
	last_editor_display_name NVARCHAR2(40) NULL,
	last_editor_user_id NUMBER NULL,
	owner_user_id NUMBER NULL,
	parent_id NUMBER NULL,
	post_type_id NUMBER NOT NULL,
	score NUMBER NOT NULL,
	tags NVARCHAR2(150) NULL,
	title NVARCHAR2(250) NULL,
	view_count NUMBER NOT NULL,
	body NCLOB NOT NULL,
	CONSTRAINT posts_pk PRIMARY KEY (post_id),
	/* TODO: Should these be indexes? */
	CONSTRAINT posts_accepted_uq UNIQUE (post_id, accepted_answer_id),
	CONSTRAINT posts_parent UNIQUE(post_id, parent_id)
);

CREATE TABLE DUMMY.comments (
	comment_id NUMBER GENERATED ALWAYS AS IDENTITY,
	created_at TIMESTAMP NOT NULL,
	post_id NUMBER NOT NULL,
	score NUMBER NULL,
	user_id NUMBER NULL,
	text NVARCHAR2(700) NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (comment_id)
);

CREATE TABLE DUMMY.badges (
	badge_id NUMBER GENERATED ALWAYS AS IDENTITY,
	name NVARCHAR2(40) NOT NULL,
	user_id NUMBER NOT NULL,
	date_awarded TIMESTAMP NOT NULL,
	CONSTRAINT badges_pk PRIMARY KEY (badge_id)
);

CREATE TABLE DUMMY.post_links (
	post_link_id NUMBER GENERATED ALWAYS AS IDENTITY,
	created_at TIMESTAMP NOT NULL,
	post_id NUMBER NOT NULL,
	related_post_id NUMBER NOT NULL,
	link_type_id NUMBER NOT NULL,
	CONSTRAINT post_links_pk PRIMARY KEY (post_link_id)
);

/* TODO: Add foreign keys */

COMMIT;